
ALTER TABLE COMMANDE ADD
    CONSTRAINT FK_COM_Cli
    FOREIGN KEY(CodeCli)
    REFERENCES CLIENT(CodeCli);

ALTER TABLE HISTORIQUE_PRIX ADD
    CONSTRAINT FK_HP_Art
    FOREIGN KEY(CodeArt)
    REFERENCES ARTICLE(CodeArt);

ALTER TABLE ARTICLE ADD
    CONSTRAINT FK_ART_Cat
    FOREIGN KEY(CodeCat)
    REFERENCES CATEGORIE(CodeCat);

ALTER TABLE ACHETER ADD
    CONSTRAINT FK_ACH_Art
    FOREIGN KEY(CodeArt)
    REFERENCES ARTICLE(CodeArt);
ALTER TABLE ACHETER ADD
    CONSTRAINT FK_ACH_Comm
    FOREIGN KEY(CodeComm)
    REFERENCES COMMANDE(CodeComm);
